name: Test

on: push

jobs:
  test:
    name: "PHPUnit (PHP ${{ matrix.php-versions }})"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ["8.4"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php-versions }}"

      - name: Install Composer
        run: composer update --no-progress --prefer-dist --optimize-autoloader

      - name: Run Tests
        run: composer run test

      - name: Run Static Analysis
        run: composer run analyse
